### ISSUE TITLE
error with inn

### ISSUE THREAD

**Issue by Owenm05** [Areso/1255-burgomaster#695]
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at updateHeroStatusInn (inn.js:68:49)
    at updateHeroStatus (dom.js:2:2)
    at updateUI ((index):5086:53)
    at Object.calculateTurn ((index):3431:4)
    at endOfTurnTimer ((index):5200:9)
    at sentryWrapped (helpers.ts:84:17)

**Comment by Voldus** [comment]
My PR contains fix for that issue.
